apps/nlp/views.py
import json
import os
from flask import Blueprint, render_template, request, jsonify, current_app, abort
from flask_login import login_required, current_user
from functools import wraps
from werkzeug.utils import secure_filename
from engines.bert_similarity.bertsimilarity import BertSimilarity
from engines.bert_translation.translation import TextTranslation
from engines.bert_ner.ner import NamedEntityRecognition
from engines.bert_qa.qa import QA
from engines.bert_classification.classification import Classification
from engines.bert_textgeneration.textgeneration import TextGenerate
import time
from queue import Queue
import threading

nlp_bp = Blueprint("nlp", __name__, url_prefix='/nlp')
q = Queue()

def need_permission(perm):
    # 自定义装饰器：角色权限访问控制装饰器
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            if not current_user.can(perm):
                abort(403)
            return func(*args, **kwargs)
        return wrapper
    return decorator


def train_func(app, content, file_path, q):
    with app.app_context():
        bert_classification = Classification(os.getcwd() + "/engines/models/", file_path)
        bert_classification.train(content["feature"], content["label"], float(content["frac"]), int(content["epoch"]), q)


@nlp_bp.route('/SentenceSimilarity/', methods=['GET', 'POST'])
def SentenceSimilarity():
    if request.method == "POST":
        data = {}
        for item in request.form.lists():
            data[item[0]] = item[1]
        t1 = time.time()
        bert_similarity = BertSimilarity(os.getcwd() + "/engines/models/text2vec_base_chinese")
        result = bert_similarity.compute(data)
        result["time_cost"] = round(time.time() - t1, 2)
        del bert_similarity
        return json.dumps(result)

    return render_template("nlp/SentenceSimilarity.html")


@nlp_bp.route('/NER/', methods=['GET', 'POST'])
def NER():
    if request.method == "POST":
        content = list(request.form.lists())
        result = {}
        t1 = time.time()
        if content[0][1][0] == '#text1':
            bert_ner = NamedEntityRecognition(os.getcwd() + "/engines/models/bert-base-chinese",
                           os.getcwd() + "/engines/models/ckiplab/bert-base-chinese-ner")
            result["ans"] = bert_ner.compute(content[0][1][1])
            del bert_ner
        if content[0][1][0] == '#text2':
            bert_pos = NamedEntityRecognition(os.getcwd() + "/engines/models/bert-base-chinese",
                           os.getcwd() + "/engines/models/ckiplab/bert-base-chinese-pos")
            result["ans"] = bert_pos.compute_pos(content[0][1][1])
            del bert_pos
        result["time_cost"] = round(time.time() - t1, 2)
        return json.dumps(result)

    return render_template("nlp/NER.html")


@nlp_bp.route('/Translation/', methods=['GET', 'POST'])
def Translation():
    if request.method == "POST":
        content = list(request.form.lists())
        result = {}
        t1 = time.time()
        if content[0][1][0] == '#text1':
            bert_translation_zh_en = TextTranslation(os.getcwd() + "/engines/models/Helsinki-NLP/opus-mt-zh-en")
            result = bert_translation_zh_en.translation(content[0][1][1])[0]
            del bert_translation_zh_en
        if content[0][1][0] == '#text2':
            bert_translation_en_zh = TextTranslation(os.getcwd() + "/engines/models/Helsinki-NLP/opus-mt-en-zh")
            result = bert_translation_en_zh.translation(content[0][1][1])[0]
            del bert_translation_en_zh
        result["time_cost"] = round(time.time() - t1, 2)
        return json.dumps(result)

    return render_template("nlp/Translation.html")


@nlp_bp.route('/QuestionAnswering/', methods=['GET', 'POST'])
def QuestionAnswering():
    if request.method == "POST":
        content = request.form.to_dict()
        result = {}
        t1 = time.time()
        bert_qa = QA(os.getcwd() + "/engines/models/uer/roberta-base-chinese-extractive-qa")
        result["ans"] = bert_qa.compute(content["context"], content["question"])["answer"]
        del bert_qa
        result["time_cost"] = round(time.time() - t1, 2)
        return json.dumps(result)

    return render_template("nlp/QA.html")


@nlp_bp.route('/TextClassification/', methods=['GET', 'POST'])
def TextClassification():
    content = request.form.to_dict()
    # 预测
    if request.method == "POST" and content.get("context") is not None:
        result = {}
        t1 = time.time()
        bert_classification = Classification(os.getcwd() + "/engines/models/")
        result["ans"] = bert_classification.compute(content["context"])
        del bert_classification
        result["time_cost"] = round(time.time() - t1, 2)
        return json.dumps(result)

    return render_template("nlp/TextClassification.html", dataview="")


@nlp_bp.route('/TextClassificationTrainer/', methods=['GET', 'POST'])
@login_required
@need_permission(Permission.MODEL)
def TextClassificationTrainer():
    content = request.form.to_dict()
    file_path = os.getcwd() + "/engines/datasets/job_detail_file.txt"
    # 上传数据
    if request.method == "POST" and content.get("sep") is not None:
        files = request.files.get("customerfile")
        if request.form.get("sep") == "1":
            sep = ","
        else:
            sep = "\t"

        if files.filename != '':
            file_path = os.path.join(current_app.config['UPLOAD_DIR'], secure_filename(files.filename))
            files.save(file_path)

        dataview = []
        with open(file_path, "r", encoding="utf-8-sig") as r:
            header = r.readline().strip("\n").split(sep)
            dataview.append(header)
            for i in range(5):
                line = r.readline().strip("\n").split(sep)[:len(header)]
                dataview.append(line)
        return render_template("nlp/TextClassificationTrainer.html", dataview=dataview)
    # 训练
    if request.method == "POST" and len(content) > 1:
        result = {}
        t1 = time.time()
        # 新线程后台训练
        app = current_app._get_current_object()
        thr = threading.Thread(name="train_thread", target=train_func, args=[app, content, file_path, q])
        # thr.daemon = 1
        thr.start()
        result["time_cost"] = round(time.time() - t1, 2)
        return jsonify(result)
    return render_template("nlp/TextClassificationTrainer.html", dataview="")


@nlp_bp.route('/getlog/', methods=['GET', 'POST'])
def getlog():
    # print(threading.activeCount())
    # print(threading.enumerate())
    if q.empty():
        return jsonify({"data": "empty"})
    else:
        a = q.get()  # get不到会阻塞
        return jsonify({"data": a})


@nlp_bp.route('/TextGeneration/', methods=['GET', 'POST'])
def TextGeneration():
    if request.method == "POST":
        content = request.form.to_dict()
        result = {}
        t1 = time.time()
        bert_textgeneration = TextGenerate(os.getcwd() + "/engines/models/uer/gpt2-chinese-cluecorpussmall")
        result["ans"] = bert_textgeneration.compute(content["context"])[0]["generated_text"]
        del bert_textgeneration
        result["time_cost"] = round(time.time() - t1, 2)
        return json.dumps(result)

    return render_template("nlp/TextGeneration.html")

templates/nlp/NER.html
{% extends "base.html"%}

{% block title %}命名实体识别{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <label>命名实体识别</label>
                <br>
                <textarea id="text1" class='form-control' placeholder='在此输入文本'></textarea>
                <button id= "compute1" class="btn btn-dark" style="width: 6rem" type="button" onclick="compute(this, '#result1', '#text1')">计算</button>

                <div id="result1"></div>

            </div>

            <div class="col">
                <label>词性识别</label>
                <br>
                <textarea id="text2" class='form-control' placeholder='在此输入文本'></textarea>
                <button id= "compute" class="btn btn-dark" style="width: 6rem" type="button" onclick="compute(this, '#result2', '#text2')">计算</button>

                <div id="result2"></div>

            </div>

{#            <div class="col">#}
{#                <label>分词识别</label>#}
{#                <br>#}
{#                <textarea id="text3" class='form-control' placeholder='在此输入文本'></textarea>#}
{#                <button id= "compute" class="btn btn-dark" style="width: 6rem" type="button" onclick="compute(this, '#result3', '#text3')">计算</button>#}
{##}
{#                <div id="result3"></div>#}
{##}
{#            </div>#}

        </div>
    </div>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}
<script>
    function compute(btn, result, content) {
        // 计算按钮先变成加载状态
        var compute_button = $(btn)
        compute_button.prop("disabled", true)
        compute_button.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>')

        // 清空结果div
        $(result).empty()

        // ajax 请求数据
        var text = $(content).val()
        $.post("{{ url_for('nlp.NER') }}", {'content':[content,text]}, function (data) {
            // 回复计算按钮
            compute_button.prop("disabled", false)
            compute_button.html("计算")

            // 显示结果
            {#console.log(data)#}
            var timecosthtml = "<p>计算时长：" + data["time_cost"] + "</p>"
            var ans = data["ans"]
            for (var key in ans) {
                text = text.replaceAll(key, '<span style="background-color: rgb(191, 237, 210);">' + ans[key] + '</span>')
            }
            $(result).html(timecosthtml + text)
        }, "json")
    }

</script>
{% endblock %}

templates/nlp/QA.html
{% extends "base.html"%}

{% block title %}文本问答{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <label>文本问答</label>
                <br>
                <textarea id="text" class='form-control' placeholder='在此输入文本'></textarea>
                <textarea id="question" class='form-control' placeholder='在此输入问题'></textarea>
                <button id= "compute" class="btn btn-dark" style="width: 6rem" type="button" onclick="compute(this, '#text', '#question')">计算</button>

                <div id="result"></div>

            </div>

        </div>
    </div>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}
<script>
    function compute(btn, text, question) {
        // 计算按钮先变成加载状态
        var compute_button = $(btn)
        compute_button.prop("disabled", true)
        compute_button.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>')

        // 清空结果div
        $('#result').empty()

        // ajax 请求数据
        var text = $(text).val()
        var question = $(question).val()
        $.post("{{ url_for('nlp.QuestionAnswering') }}", {'context':text, 'question':question}, function (data) {
            // 回复计算按钮
            compute_button.prop("disabled", false)
            compute_button.html("计算")

            // 显示结果
            {#console.log(data)#}
            var timecosthtml = "<p>计算时长：" + data["time_cost"] + "</p>"
            var ans = data["ans"]
            $('#result').html(timecosthtml + ans)
        }, "json")
    }

</script>
{% endblock %}

templates/nlp/SentenceSimilarity.html
{% extends "base.html"%}

{% block title %}文本相似度{% endblock %}

{% block main %}
    <form>
        <p>
            <label>主文本</label>
            <label>
                <input class='form-control' name='source-sentence' placeholder='在此输入主文本' type='text'>
            </label>
        </p>

        <p>
            <label>对比文本</label>
            <label>
                <input class='form-control' name='compare-sentence' placeholder='在此输入对比文本' type='text'>
            </label>
        </p>

        <button id= "addSentence" class="btn btn-dark" type="button">添加句子</button>
        <button id= "compute" class="btn btn-dark" style="width: 6rem" type="button">计算</button>

        <div id="result"></div>

    </form>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}
<script>
    // TODO: jquery 文本不为空

    // 动态添加表单栏
    var t = "<p><input class='form-control' name='compare-sentence' placeholder='在此输入对比文本' type='text'></p>"
    $("#addSentence").click(function () {
        $(this).before(t)
    })

    // 点击计算上传数据
    $("#compute").click(function () {
        // 计算按钮先变成加载状态
        var compute_button = $(this)
        compute_button.prop("disabled", true)
        compute_button.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>')

        // 清空结果div
        $("#result").empty()

        // ajax 请求数据
        var text = $("form").serialize()  {# 将form里的内容序列化 #}

        $.post("{{ url_for('nlp.SentenceSimilarity') }}", text, function (data) {
            // 回复计算按钮
            compute_button.prop("disabled", false)
            compute_button.html("计算")

            // 显示结果
            {#console.log(data)#}
            var timecosthtml = "<p>计算时长：" + data["time_cost"] + "</p>"
            var content = ""
            for(let i=0; i < data["compare-sentence"].length; i++){
                content += '<p>' + data["compare-sentence"][i] + ': ' + data["score"][i+1] + '</p>'
            }
            var result = timecosthtml
            $("#result").html(result + content)
        }, "json")
    })

</script>
{% endblock %}

templates/nlp/TextClassification.html
{% extends "base.html"%}

{% block title %}文本分类{% endblock %}

{% block main %}
    <div class="container">
        {# 预测 #}
        <div class="row">
            <div class="col">
                <label>文本分类</label>
                <br>
                <textarea id="text" class='form-control' placeholder='在此输入文本'></textarea>
                <button id= "compute" class="btn btn-dark" style="width: 6rem" type="button" onclick="compute(this, '#text')">计算</button>

                <div id="result"></div>

            </div>
        </div>
    </div>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

<script src="{{ url_for('static', filename='js/Chart.min.js') }}"></script>

<script>
    function compute(btn, text) {
        // 计算按钮先变成加载状态
        var compute_button = $(btn)
        compute_button.prop("disabled", true)
        compute_button.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>')

        // 清空结果div
        $('#result').empty()

        // ajax 请求数据
        var text = $(text).val()
        $.post("{{ url_for('nlp.TextClassification') }}", {'context':text}, function (data) {
            // 恢复计算按钮
            compute_button.prop("disabled", false)
            compute_button.html("计算")

            // 显示结果
            {#console.log(data)#}
            var timecosthtml = "<p>计算时长：" + data["time_cost"] + "</p>"
            var ans = data["ans"]
            $('#result').html(timecosthtml + ans)
        }, "json")
    }
</script>
{% endblock %}

templates/nlp/TextClassificationTrainer.html
{% extends "base.html"%}

{% block title %}文本分类训练器{% endblock %}

{% block main %}
    <div class="container">
        {# 训练 #}
        <label>训练器</label>
        <form action="{{ url_for('nlp.TextClassificationTrainer') }}" method="post" enctype="multipart/form-data">
            <input id="customerfile" name="customerfile" type="file">
            <br>
            <label>分隔符</label>
            <select id="sep" name="sep">
                <option value="1">逗号</option>
                <option value="2">制表符</option>
            </select>
            <button id="submit" type="submit">上传</button>
        </form>

        <label>数据预览</label>
        <div>
            <table id="dataview" border="1">
            </table>
        </div>

        <label>目标</label>
        <select id="label" name="label">
                <option value="1">字段1</option>
                <option value="2">字段2</option>
        </select>

        <label>特征</label>
        <select id="feature" name="feature">
                <option value="1">字段1</option>
                <option value="2">字段2</option>
        </select>

        <label>取样比例</label>
{#        <input type="range" class="form-control-range" id="frac" min="1" max="100" value="10">#}
        <input id="frac" type="text" min="1" max="100" value="0.01" placeholder="输入取样比例（1-100）">

        <label>epochs</label>
        <input id="epoch" type="text" min="1" max="50" value="10" placeholder="10">

        {# 训练按钮 #}
        <button id= "train" class="btn btn-dark" style="width: 6rem" type="button" onclick="train(this)">训练</button>

        {# 训练日志 #}
        <div id="trainLog"></div>

        {# 进度条 #}
        <div class="progress">
          <div id="trainProgress" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
        </div>

        <canvas id="myChart" width="50" height="50"></canvas>
    </div>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

<script src="{{ url_for('static', filename='js/Chart.min.js') }}"></script>

<script>
    {# 训练过程 #}
    function train(btn){
        // 多线程
        /*
        var worker = new Worker("{{ url_for('static', filename='js/redisQueueWorker.js') }}");
        worker.postMessage("{{ url_for('nlp.getlog') }}");
        worker.onmessage = function (e) {
            if(e.data == 5) {
                worker.terminate();
            }
        }
        */

        // 计算按钮先变成加载状态
        var compute_button = $(btn)
        compute_button.prop("disabled", true)
        compute_button.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>')

        // 获取选项
        var label = $("#label option:selected").text();
        var feature = $("#feature option:selected").text();
        var frac = $("#frac").val();
        var epoch = $("#epoch").val();
        var trainProgress = $('#trainProgress');
        trainProgress.attr({"style": "width:0%", "aria-valuenow":"0"});
        trainProgress.text("0%");

        // 启动训练线程
        $.post("{{ url_for('nlp.TextClassificationTrainer') }}", {'label':label, 'feature':feature, 'frac':frac, 'epoch':epoch})

        // 获取训练日志队列
        var num = "";
        var trainLog = "";
        var inter = setInterval(function () {
            $.get("{{ url_for('nlp.getlog') }}", function (res) {
                // console.log(res)
                if (res["data"] !== "empty") {
                    num = res["data"].match(/\d+/)[0];

                    // 显示训练日志
                    trainLog += res["data"]
                    // $('#trainLog').html(trainLog)

                    // 进度条
                    var n = Math.trunc(((parseInt(num) + 1) / parseInt(epoch)) * 100);
                    trainProgress.attr({"style": "width:" + n.toString() + "%", "aria-valuenow":n.toString()});
                    trainProgress.text(n.toString() + "%");

                    // 最后一个批次停止循环
                    if (parseInt(num) === parseInt(epoch) - 1) {
                        compute_button.prop("disabled", false);
                        compute_button.html("训练");
                        clearInterval(inter);
                    }
                }
            });
        }, 2000);
    }

    {# 加载预览数据 #}
    $(function () {
        {# 显示后端传入的预览数据 #}
        $('#dataview').empty();
        $('#label').empty();
        $('#feature').empty();
        var table = "<tr><th>列1</th><th>列2</th></tr>";
        var col = '<option value="0">无列名</option>';

        var dataview = {{ dataview | tojson | safe }}
        if (typeof dataview === "string") {
            // 无数据
            $('#dataview').html(table);  // 预览
            $('#label').html(col);  // 列名
            $('#feature').html(col);
        } else {
            // 上传自定义数据
            table = "";
            var is_header = true;
            col = "";
            for (var i in dataview) {
                var line = "";
                for(var j in dataview[i]) {
                    line += "<th>" + dataview[i][j] + "</th>"
                    if (is_header) {
                        col += '<option value="' + j + '">' + dataview[i][j] + '</option>'
                    }
                }
                is_header = false
                table += "<tr>" + line + "</tr>";
            }
            $('#dataview').html(table);
            $('#label').html(col);  // 列名
            $('#feature').html(col);
        }
    });

    {# 训练结果图 #}
    var ctx = $("#myChart");
    const X = ['一月份', '二月份', '三月份','四月份', '五月份', '六月份', '七月份'];  // 设置 X 轴上对应的标签
    const Y = [65, 59, 80, 81, 56, 55, 40]
    const data = {
      labels: X,
      datasets: [{
        label: 'loss',
        data: Y,
        fill: false,  // 折线以下的背景颜色
        borderColor: 'rgb(75, 192, 192)', // 设置线的颜色
        tension: 0.1,  // 拐点处曲率
      }]
    };
    const config = {
      type: 'line', // 设置图表类型
      data: data,
    };
    const myChart = new Chart(ctx, config);


</script>
{% endblock %}

templates/nlp/TextGeneration.html
{% extends "base.html"%}

{% block title %}文本生成{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <label>文本生成</label>
                <br>
                <textarea id="text" class='form-control' placeholder='在此输入文本'></textarea>
                <button id= "compute" class="btn btn-dark" style="width: 6rem" type="button" onclick="compute(this, '#text')">计算</button>

                <div id="result"></div>

            </div>

        </div>
    </div>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}
<script>
    function compute(btn, text) {
        // 计算按钮先变成加载状态
        var compute_button = $(btn)
        compute_button.prop("disabled", true)
        compute_button.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>')

        // 清空结果div
        $('#result').empty()

        // ajax 请求数据
        var text = $(text).val()
        $.post("{{ url_for('nlp.TextGeneration') }}", {'context':text}, function (data) {
            // 回复计算按钮
            compute_button.prop("disabled", false)
            compute_button.html("计算")

            // 显示结果
            {#console.log(data)#}
            var timecosthtml = "<p>计算时长：" + data["time_cost"] + "</p>"
            var ans = data["ans"]
            $('#result').html(timecosthtml + ans)
        }, "json")
    }

</script>
{% endblock %}

templates/nlp/Translation.html
{% extends "base.html"%}

{% block title %}文本相似度{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <label>中文 -> 英文</label>
                <br>
                <textarea id="text1" class='form-control' placeholder='在此输入文本'></textarea>
                <button id= "compute1" class="btn btn-dark" style="width: 6rem" type="button" onclick="compute(this, '#result1', '#text1')">计算</button>

                <div id="result1"></div>

            </div>

            <div class="col">
                <label>英文 -> 中文</label>
                <br>
                <textarea id="text2" class='form-control' placeholder='在此输入文本'></textarea>
                <button id= "compute" class="btn btn-dark" style="width: 6rem" type="button" onclick="compute(this, '#result2', '#text2')">计算</button>

                <div id="result2"></div>

            </div>

        </div>
    </div>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}
<script>
    function compute(btn, result, content) {
        // 计算按钮先变成加载状态
        var compute_button = $(btn)
        compute_button.prop("disabled", true)
        compute_button.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>')

        // 清空结果div
        $(result).empty()

        // ajax 请求数据
        var text = $(content).val()
        $.post("{{ url_for('nlp.Translation') }}", {'content':[content,text]}, function (data) {
            // 回复计算按钮
            compute_button.prop("disabled", false)
            compute_button.html("计算")

            // 显示结果
            {#console.log(data)#}
            var timecosthtml = "<p>计算时长：" + data["time_cost"] + "</p>"
            var content = data["translation_text"]
            $(result).html(timecosthtml + content)
        }, "json")
    }

</script>
{% endblock %}

templates/nlp/dynamicform.html
{% extends "base.html"%}

{% block title %}文本相似度{% endblock %}

{% block main %}
    <form>
        <p>
            <label>主文本</label>
            <input class='form-control' name='source-sentence' placeholder='在此输入主文本' type='text'>
        </p>

        <p>
            <label>对比文本</label>
            <input class='form-control' name='compare-sentence' placeholder='在此输入对比文本' type='text'>
        </p>

        <button id= "addSentence" class="btn btn-dark" type="button">添加句子</button>
        <button id= "compute" class="btn btn-dark" style="width: 6rem" type="button">计算</button>

        <div id="result"></div>

    </form>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}
<script>
    // TODO: jquery 文本不为空

    // 动态添加表单栏
    var t = "<p><input class='form-control' name='compare-sentence' placeholder='在此输入对比文本' type='text'></p>"
    $("#addSentence").click(function () {
        $(this).before(t)
    })

    // 点击计算上传数据
    $("#compute").click(function () {
        // 计算按钮先变成加载状态
        var compute_button = $(this)
        compute_button.prop("disabled", true)
        compute_button.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>')

        // 清空结果div
        $("#result").empty()

        // ajax 请求数据
        var text = $("form").serialize()
        $.post("{{ url_for('nlp.dynamicform') }}", text, function (data) {
            // 回复计算按钮
            compute_button.prop("disabled", false)
            compute_button.html("计算")

            // 显示结果
            {#console.log(data)#}
            var timecosthtml = "<p>计算时长：" + data["time_cost"] + "</p>"
            var content = ""
            for(let i=0; i < data["compare-sentence"].length; i++){
                content += '<p>' + data["compare-sentence"][i] + ': ' + data["score"][i+1] + '</p>'
            }
            var result = timecosthtml
            $("#result").html(result + content)
        }, "json")
    })

</script>
{% endblock %}