apps/article/views.py
import os
import uuid

from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, g, make_response, flash, \
    abort, current_app
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from functools import wraps
from apps.article.form import *
from apps.article.model import *
from apps.auth.model import Permission
from bs4 import BeautifulSoup

article_bp = Blueprint("article", __name__, url_prefix="/article")


# 通过装饰器传参数，让装饰器自己接受参数
def need_permission(perm):
    # 自定义装饰器：角色权限访问控制装饰器
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            if not current_user.can(perm):
                abort(403)
            return func(*args, **kwargs)
        return wrapper
    return decorator


# 1.文章页
@article_bp.route('/<tag_name_en>/<int:article_id>/', methods=['GET', 'POST'])
def article_page(tag_name_en, article_id):
    article = Article.query.get_or_404(article_id)
    # 评论
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.body.data,
                          article=article,
                          user=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('评论成功')
        return redirect(url_for('article.article_page', tag_name_en=tag_name_en, article_id=article_id))
    page = int(request.args.get('page', 1))
    pagination = article.comments.order_by(
        Comment.addtime.desc()
    ).paginate(page, per_page=5)

    return render_template('article/article_page.html', article=article, form=form, pagination=pagination)


# 2.编辑文章
@article_bp.route('/article_add/', methods=['GET', 'POST'])
@login_required
@need_permission(Permission.WRITE)
def article_add():
    form = ArticlePostForm()
    edit = request.args.get('edit')
    article_id = request.args.get('article_id')

    # GET请求 并且 是编辑状态 才获取 article_id 进入编辑
    if request.method == "GET" and edit:
        article = Article.query.get_or_404(article_id)
        # 自己只能修改自己的文章
        if current_user != article.user and not current_user.can(Permission.ADMIN):
            abort(403)
        form.title.data = article.title
        # form.body.data = article.body_blob.decode('utf-8')
        form.body.data = article.body_html
        form.tag.data = article.tag_id

    if form.validate_on_submit():
        # 判断 body 是否空
        if not form.body.data:
            flash('内容不能为空', 'info')
            return render_template('article/article_add.html', form=form, edit=edit, article_id=article_id)
        if edit:
            # 旧文章修改
            article = Article.query.get_or_404(article_id)
            article.title = form.title.data
            # article.body = form.body.data
            # article.body_blob = form.body.data.encode('utf-8')
            article.body_html = form.body.data
            article.tag_id = form.tag.data
            db.session.commit()
        else:
            # 新文章入库
            article = Article(
                title=form.title.data,
                # body = form.body.data,
                # body_blob=form.body.data.encode('utf-8'),  # 富文本二进制保存
                body_html=form.body.data,  # 富文本保存html
                author_id=current_user.id,
                tag_id=form.tag.data,
            )
            db.session.add(article)
            db.session.commit()

        # 图片地址入库
        html = BeautifulSoup(form.body.data, "html.parser")
        for i in html.find_all("img"):
            image_exists = ArticleImage.query.filter_by(imgpath=i.get("src"), article_id=article.id).first()
            if not image_exists:
                # 图片相对地址保存数据库
                articleimage = ArticleImage(
                    imgpath=i.get("src"),
                    article_id=article.id,
                )
                db.session.add(articleimage)
        db.session.commit()
        flash('编辑成功!', '消息')
        # TODO: 操作日志
        # oplog = Oplog(
        #     admin_id=session['admin_id'],
        #     ip=request.remote_addr,
        #     reason='添加电影:《' + movie.title + '》'
        # )
        # db.session.add(oplog)
        # db.session.commit()
        tag = Tag.query.filter_by(id=form.tag.data).first()
        return redirect(url_for('article.article_page', tag_name_en=tag.tag_name_en, article_id=int(article.id)))

    return render_template('article/article_add.html', form=form, edit=edit, article_id=article_id)


# 3.文章列表
@article_bp.route('/<tag_name_en>/', methods=['GET', 'POST'])
@login_required
@need_permission(Permission.WRITE)
def article_list(tag_name_en):
    # # join关联，先 TAG表限定英文标签名
    # # 再 用限定后的 Tag.id 关联 Article.tag_id
    articles = Article.query.join(Tag).filter(
        Tag.tag_name_en == tag_name_en,
        Article.tag_id == Tag.id
    ).all()
    # flash('测试一下闪现!', 'warning')
    flash('测试一下闪现! info', 'info')
    return render_template("article/article_list.html", articles=articles)


# 4.删除文章
@article_bp.route("/article_del/", methods=["GET"])
@login_required
@need_permission(Permission.WRITE)
def article_del():
    article_id = request.args.get("article_id")
    tag_name_en = request.args.get("tag_name_en")

    article = Article.query.filter_by(id=article_id).first_or_404()
    # 删除文章中的图片
    articleimages = ArticleImage.query.filter_by(article_id=article_id).all()
    for i in articleimages:
        file_path = current_app.config['BASE_DIR'] + i.imgpath
        if os.path.exists(file_path):
            os.remove(file_path)
    ArticleImage.query.filter_by(article_id=article_id).delete()

    # 删除文章
    db.session.delete(article)
    db.session.commit()
    flash('删除文章成功!', 'warning')

    # # 将删除电影操作保存到操作日志列表
    # oplog = Oplog(
    #     admin_id=session['admin_id'],
    #     ip=request.remote_addr,
    #     reason='删除电影:《' + movie.title + '》'
    # )
    # db.session.add(oplog)
    # db.session.commit()
    return redirect(url_for("article.article_list", tag_name_en=tag_name_en))


# 5.图片上传
@article_bp.route("/picture/", methods=["GET", "POST"],  strict_slashes=False)  # strict_slashes=False : 不会再 严格的要求 斜杠
@login_required
@need_permission(Permission.WRITE)
def picture():
    file = request.files.get("file")
    article_id = request.args.get("article_id")
    # TODO：云存储
    if file:
        # timce 自带图片验证，非图像传不上来
        # file_name = secure_filename(file.filename)
        file_name = uuid.uuid4().hex + "." + file.filename.split(".")[-1]
        print(file_name)
        relative_path = "upload/article_image/"
        file_path = os.path.join(current_app.config['STATIC_DIR'], relative_path)
        if not os.path.exists(file_path):
            os.makedirs(file_path)
        file.save(file_path + file_name)

        location = url_for("static", filename=relative_path + file_name)
        return jsonify({"location": location})  # 返回 location 存放图片url
    return "ok"


# 1.所有人的博客
@article_bp.route('/show_all/')
@login_required
def show_all():
    # make_response 创建响应对象，指定好 cookie 后重定向到首页
    resp = make_response(redirect(url_for('user.index')))
    resp.set_cookie('show_followed', '', max_age=30*24*60*60)
    return resp


# 2.关注人的博客
@article_bp.route('/show_followed/')
@login_required
def show_followed():
    # make_response 创建响应对象，指定好 cookie 后重定向到首页
    resp = make_response(redirect(url_for('user.index')))
    resp.set_cookie('show_followed', '1', max_age=30*24*60*60)
    return resp


# 1.评论列表
@article_bp.route("/comment_list/", methods=["GET"])
@login_required
@need_permission(Permission.MODERATE)
def comment_list():
    page = int(request.args.get('page', 1))
    pagination = Comment.query.order_by(
        Comment.addtime.desc()
    ).paginate(page, per_page=5)
    return render_template("article/comment_list.html", pagination=pagination, page=page)


# 2.编辑评论
@article_bp.route("/comment_edit/<int:comment_id>/", methods=["GET"])
@login_required
@need_permission(Permission.MODERATE)
def comment_edit(comment_id):
    status = request.args.get('status', 1)
    page = int(request.args.get('page', 1))
    comment = Comment.query.get_or_404(comment_id)
    if status:
        comment.disabled = True
    else:
        comment.disabled = False
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for("article.comment_list", page=page))


# """收藏管理"""
# # 1.收藏列表
# @article_bp.route("/article/moviecol_list/", methods=["GET"])
# def moviecol_list():
#     page = int(request.args.get('page', 1))
#     auth_page = Moviecol.query.join(Movie).join(User).filter(
#         Movie.id == Moviecol.movie_id,
#         User.id == Moviecol.user_id
#     ).order_by(
#         Moviecol.addtime.desc()
#     ).paginate(page=page, per_page=2)
#     return render_template("movie/moviecol.html", auth_page=auth_page)
#
#
# # 2.删除收藏
# @article_bp.route("/article/moviecol_del/", methods=["GET"])
# def moviecol_del():
#     id = request.args.get("id")
#     moviecol = Moviecol.query.filter_by(id=id).first_or_404()
#     db.session.delete(moviecol)
#     db.session.commit()
#     flash('删除收藏成功!', 'warning')
#     return redirect(url_for("article.moviecol", page=1))

templates/article/article_add.html
{% extends "base.html"%}

{% block title %}添加文章{% endblock %}

{% block main %}

    <div id="role">
        {# wtf.from_field(form.body) #}
        <form action="{% if edit %} {{ url_for('article.article_add', article_id=article_id, edit=edit) }} {% else %} {{ url_for('article.article_add') }} {% endif %}" method="post" enctype="multipart/form-data">

            <p>{{ form.title.label }}{{ form.title }}</p>
                {% for message in form.title.errors %}
                        <small class="error">{{ message }}</small><br>
                {% endfor %}

            <p>{{ form.body.label }}{{ form.body }}</p>
                {% for message in form.body.errors %}
                        <small class="error">{{ message }}</small><br>
                {% endfor %}

            <p>{{ form.tag.label }}{{ form.tag }}</p>
                {% for message in form.tag.errors %}
                        <small class="error">{{ message }}</small><br>
                {% endfor %}

            <p>{{ form.submit }}{{ form.csrf_token }}</p>

          </form>

    </div>


{% endblock %}


<!--js脚本-->
{% block scripts %}
    {{ super() }}
    {# 富文本编辑器tinymce #}
    <script src="{{ url_for('static', filename='extends/tinymce_6.1.0/tinymce.min.js') }}"></script>
    <script>
        tinymce.init({
            selector: '.content_area',  //容器，可使用css选择器
            language:'zh-Hans', //调用放在langs文件夹内的语言包
            {#toolbar: false, //隐藏工具栏#}
            {#menubar: false, //隐藏菜单栏#}
            {#inline: true, //开启内联模式#}
            {#height:400,  //高度为400， 有 autoresize 代替#}
            auto_focus: true,  // 让编辑器加载完成后自动获得光标焦点
            branding: false,  // 隐藏编辑器界面右下角的“Powered by Tiny”
            // 插件栏文件 plugins
            plugins: 'quickbars preview fullscreen searchreplace pagebreak insertdatetime ' +
                'autolink link anchor image media template code codesample table charmap emoticons ' +
                'visualblocks visualchars nonbreaking ' +
                'code kityformula-editor indent2em ' +
                'lists advlist wordcount help autosave autoresize',
            // 工具栏
            toolbar: [
                'styles fontsize fontfamily | indent2em alignleft aligncenter alignright lineheight outdent indent bullist numlist',
                'restoredraft searchreplace | codesample table image media charmap emoticons hr pagebreak insertdatetime | code kityformula-editor',
            ],
            // 右键菜单
            contextmenu: "cut copy paste pastetext indent2em link anchor",
            // quickbars
            quickbars_selection_toolbar: "forecolor backcolor styles fontsize | indent2em lineheight removeformat",
            quickbars_insert_toolbar:"",
            // 上传图片后端处理地址
            images_upload_url:{% if article_id %}"/article/picture?article_id=" + {{ article_id }} {% else %} "/article/picture" {% endif %},  // 选择好图片后的路由地址
            relative_urls: false,  // 禁用图片相对路径地址，否则前端会加上 路由的prefix
            {#images_upload_base_path:"",  #}
            // 编辑区内的css：限制图片大下 行高
            content_style:"img {max-width: 1280px; max-height: 760px}",
            //字体大小
            font_size_formats: '12px 14px 16px 18px 24px 36px 48px 56px 72px',
            font_family_formats: '微软雅黑=Microsoft YaHei,Helvetica Neue,PingFang SC,sans-serif;苹果苹方=PingFang SC,Microsoft YaHei,sans-serif;宋体=simsun,serif;仿宋体=FangSong,serif;黑体=SimHei,sans-serif;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;',
            line_height_formats: '0.5 1 1.2 1.5 1.6 1.8 2 2.4', // 行高定义

            //按tab不换行
            nonbreaking_force_tab: true,
            codesample_global_prismjs:true
        });
    </script>

{% endblock %}

templates/article/article_list.html
{% extends "base.html"%}

{% block title %}文章列表{% endblock %}


{% block main %}

    <div id="article_list">
        {% if articles %}
            <h3>{{ articles[0].tag.tag_name }}</h3>
        {% endif %}
        <table>
{#            <tr>#}
{#                <th>编号</th>#}
{#                <th>文章名</th>#}
{#                <th>标签</th>#}
{#                <th>星级</th>#}
{#                <th>阅读量</th>#}
{#                <th>作者</th>#}
{#                <th>评论数量</th>#}
{#                <th>上映时间</th>#}
{#                <th>操作事项</th>#}
{#            </tr>#}
            {% for v in articles %}
            <tr>
{#                <td>{{ v.id }}</td>#}
                <td>
                    <a class="text-success" href="{{ url_for("article.article_page", tag_name_en=v.tag.tag_name_en, article_id=v.id) }}">{{ v.title }}</a>
                </td>
{#                <td>{{ v.tag.tag_name }}</td>#}
{#                <td>{{ v.star }}</td>#}
{#                <td>{{ v.read_num }}</td>#}
{#                <td>{{ v.user.name }}</td>#}
{#                <td>{{ v.comment_num }}</td>#}
{#                <td>{{ v.addtime }}</td>#}

                {# 管理员能编辑修改 #}
                {% if current_user.can(Permission.ADMIN) %}
                <td>
                    <a href="{{ url_for('article.article_add', article_id=v.id, edit=1) }}">编辑</a>
                    <a href="{{ url_for('article.article_del', article_id=v.id, tag_name_en=v.tag.tag_name_en) }}">删除</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>


{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

{% endblock %}

templates/article/article_page.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}
{% import "ui/list_page.html" as pg%}
{% block title %}添加文章{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        ul.comments {
            list-style-type: none;
            padding: 0px;
            margin: 16px 0px 0px 0px;
        }
        ul.comments li.comment {
            margin-left: 32px;
            padding: 8px;
            border-bottom: 1px solid #e0e0e0;
        }
        ul.comments li.comment:nth-child(1) {
            border-top: 1px solid #e0e0e0;
        }
        ul.comments li.comment:hover {
            background-color: #f0f0f0;
        }
        div.comment-date {
            float: right;
        }
        div.comment-author {
            font-weight: bold;
        }
        div.comment-thumbnail {
            position: absolute;
        }
        div.comment-content {
            margin-left: 48px;
            min-height: 48px;
        }
        .right-scrollsp {
            position: sticky;  {# 粘贴位置：基于用户的滚动位置来定位 #}
            position: -webkit-sticky;
            top:4rem;  {# 指定 left right top bottom 之一，粘贴位置才能生效 #}
            height: calc(100vh - 4rem);
        }
    </style>
{% endblock %}

{% block links %}
    {{ super() }}
    {# 前端渲染彩色代码块prism #}
    <link type="text/css" href="{{ url_for('static', filename='extends/prism/prism.css') }}" rel="stylesheet">
{% endblock %}

{% block breadcrumb %}
    {% if article %}
        <div class="border-bottom text-left p-3">
            »
            <a class="text-success" href="{{ url_for('article.article_list', tag_name_en=article.tag.tag_name_en) }}">{{ article.tag.tag_name }}</a>
            /
            <a>{{ article.title }}</a>
        </div>
    {% endif %}
{% endblock %}

{% block main %}
    {% with msgs = get_flashed_messages(with_categories=True) %}
      {% if msgs %}
          <ul id="flashToasts" hidden>
              {% for category, msg in msgs %}
                  <li class="{{ category }}" >{{ msg }}</li>
              {% endfor %}
          </ul>
      {% endif %}
    {% endwith %}

    {# Flex布局：flex-grow-1 会弹性的利用空间 #}
    {# data-spy="scroll" 滚动监听 #}
    {# data-target="#navbar-example" 滚动监听 #}
    <div id="article-content" class="flex-grow-1">

        <h1>{{ article.title }}</h1>  {# 标题 #}

        <p>
            <strong>作者：</strong><a class="text-success" href="#">{{ article.user.name }}</a><br>
            <strong>发布时间：</strong>{{ article.addtime }}<br>
            <strong>星级：</strong>{{ article.star }}
            <strong>浏览量：</strong>{{ article.read_num }}
            <strong>评论量：</strong>{{ article.comment_num }}
        </p>

        <p>
            {# 固定地址 #}
            <a class="badge badge-light" href="{{ url_for('article.article_page', tag_name_en=article.tag.tag_name_en, article_id=article.id) }}">
                文章地址
            </a>

            <span style="padding-left: 1rem; padding-right: 1rem">•</span>

            {# 自己或管理员可见 #}
            {% if article.user == current_user or current_user.can(Permission.ADMIN)%}
                <a class="badge badge-info" href="{{ url_for('article.article_add', article_id=article.id, edit=1) }}">
                    <strong>编辑</strong>
                </a>
            {% endif %}
        </p>

        <hr>
        {# 内容 #}
       <div>
    {#        {%  if article.body_html %}#}
    {#            {{ article.body_html | safe }}  {# safe 不转译HTML元素 #}
    {#        {% else %}#}
    {#            {{ article.body_blob.decode('utf-8') | safe }}#}
    {#        {% endif %}#}
            {{ article.body_html | safe }}  {# safe 不转译HTML元素 #}
       </div>

        {# 评论 #}
        <div>
            {# id="comments" 提供url片段标记 #}
            <h4 id="comments">Comments</h4>
            {% if current_user.can(Permission.COMMENT) %}
                <div>
                    {{ wtf.quick_form(form) }}
                </div>
            {% endif %}
            {% include 'ui/_comments.html' %}
            {# #comments url片段#用来标记滚动条起始位置 #}
            {# 使得翻页时候能直接定位再评论位置 #}
            {{ pg.page(pagination, "article.article_page", fragment='#comments', article_id=article.id, tag_name_en=article.tag.tag_name_en) }}
        </div>

    </div>

    {# Display属性：.d-none .d-xl-block 只在 xl 尺寸的屏幕上显示 #}
    {# 滚动监听toc #}
    <nav id="article-toc" class="navbar navbar-light bg-light right-scrollsp d-xl-block col-xl-3">
        <nav id="content-toc" class="nav nav-pills flex-column">
{#        <a class="nav-link p-0" href="#title0">Item 1</a>#}
{#        <nav class="nav nav-pills flex-column">#}
{#          <a class="nav-link ml-3 my-1" href="#item-1-1">Item 1-1</a>#}
{#          <a class="nav-link ml-3 my-1" href="#item-1-2">Item 1-2</a>#}
{#        </nav>#}
{#        <a class="nav-link" href="#item-2">Item 2</a>#}
{#        <a class="nav-link" href="#item-3">Item 3</a>#}
{#        <nav class="nav nav-pills flex-column">#}
{#          <a class="nav-link ml-3 my-1" href="#item-3-1">Item 3-1</a>#}
{#          <a class="nav-link ml-3 my-1" href="#item-3-2">Item 3-2</a>#}
{#        </nav>#}
        </nav>
    </nav>

{% endblock %}


<!--js脚本-->
{% block scripts %}
    {{ super() }}
    {# 前端渲染彩色代码块prism #}
    <script src="{{ url_for('static', filename='extends/prism/prism.js') }}"></script>

    {# 文章导航插件 #}
    <script>
        {# dom准备好后，给h1h2h3添加id，并生成目录 #}
        var titleListMap = {};  // 记录每个 #title H标签层级关系
        $(function () {
            {# 先对h标签添加id #}
            var tempH1 = "";
            var tempH2 = "";
            $("h1, h2, h3").each(function (i) {
                {#console.log($(this).get(0).tagName)#}
                $(this).attr("id", "title" + i);  // 添加id
                // titleLocMap["title" + i] = $(this).get(0).tagName;  // 记录标题元素的id字典
                // titleLocMap["title" + i] = $(this).offset().top;  // offset(): 获取匹配元素在当前视口的相对top、left的偏移。
                if ($(this).get(0).tagName === "H1") {
                    titleListMap["title" + i] = {};
                    tempH1 = "title" + i;
                }
                if ($(this).get(0).tagName === "H2" && tempH1 !== "") {
                    titleListMap[tempH1]["title" + i] = [];
                    tempH2 = "title" + i;
                }
                if ($(this).get(0).tagName === "H3" && tempH2 !== "") {
                    titleListMap[tempH1][tempH2].push("title" + i);
                }
            })

            {# TOC #}
            console.log(titleListMap);
            $.each(titleListMap, function (h1, h2map) {
                {# 添加H1 #}
                var h1tag = $('#' + h1);
                var elementsH1 = "<a class='nav-link p-0' href='#" + h1 +  "'>" + h1tag.html() + "</a>";
                $("#content-toc").append(elementsH1);
                {# 添加H2 #}
                var h2content = "";
                if (Object.getOwnPropertyNames(h2map).length > 0) {
                    $.each(h2map, function (h2, h3List) {
                        var h2tag = $('#' + h2);
                        var elementsH2 = "<a class='nav-link ml-3 mt-1 p-0' href='#" + h2 +  "'>" + h2tag.html() + "</a>";
                        h2content += elementsH2;
                        {# 添加H3 #}
                        if (h3List.length > 0) {
                            var h3content = "";
                            for (var i = 0; i < h3List.length; i++) {
                                var h3tag = $('#' + h3List[i]);
                                var elementsH3 = "<a class='nav-link ml-4 p-0' href='#" + h3List[i] +  "'>" + h3tag.html() + "</a>";
                                h3content += elementsH3
                            }
                            var elements3Nav = "<nav class='nav nav-pills flex-column'> " + h3content + "</nav>";
                            h2content += elements3Nav
                        }
                    });
                    var elements2Nav = "<nav class='nav nav-pills flex-column'> " + h2content + "</nav>";
                    $("#content-toc").append(elements2Nav);
                }
            })

            {# data-spy="scroll" data-target="#article-toc" data-offset="1" #}
            $("body").scrollspy({
                target: '#article-toc',
                offet: 500,
            })

        })

    </script>

{% endblock %}

templates/article/comment_list.html
{% extends "base.html"%}
{% import "ui/list_page.html" as pg%}
{% block title %}评论列表{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        ul.comments {
            list-style-type: none;
            padding: 0px;
            margin: 16px 0px 0px 0px;
        }
        ul.comments li.comment {
            margin-left: 32px;
            padding: 8px;
            border-bottom: 1px solid #e0e0e0;
        }
        ul.comments li.comment:nth-child(1) {
            border-top: 1px solid #e0e0e0;
        }
        ul.comments li.comment:hover {
            background-color: #f0f0f0;
        }
        div.comment-date {
            float: right;
        }
        div.comment-author {
            font-weight: bold;
        }
        div.comment-thumbnail {
            position: absolute;
        }
        div.comment-content {
            margin-left: 48px;
            min-height: 48px;
        }
    </style>
{% endblock %}

{% block main %}
    <div class="page-header">
        <h1>Comment Moderation</h1>
    </div>
    {# 定义一个 moderate 变量，被 _comments.html 调用 #}
    {% set moderate = True %}
    {% include 'ui/_comments.html' %}
    {{ pg.page(pagination, 'article.comment_list') }}
{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}
{% endblock %}

templates/article/tag_list.html
{% extends "base.html"%}
{% import "ui/list_page.html" as pg%}

{% block title %}<title>标签列表</title>{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        .info{
            color: deepskyblue;
        }
        .warning{
            color: orange;
        }
        .error{
            color: red;
        }
    </style>
{% endblock %}

{% block middle %}

    <div id="auth_list">
        <h3 style="color:red">role_list</h3>
            {% with msgs = get_flashed_messages(with_categories=True) %}
              {% if msgs %}
                  <ul>
                      {% for category, msg in msgs %}
                          <li class="{{ category }}" >{{ msg }}</li>
                      {% endfor %}
                  </ul>
              {% endif %}
            {% endwith %}
        <table>
            <tr>
                <th>编号</th>
                <th>名称</th>
                <th>添加时间</th>
                <th>操作事项</th>
            </tr>
            {% for v in auth_page.items %}
            <tr>
                <td>{{ v.id }}</td>
                <td>{{ v.name }}</td>
                <td>{{ v.addtime }}</td>
                <td>
                    <a href="{{ url_for('article.tag_edit', id=v.id, edit_flag='edit') }}">编辑</a>
                    <a href="{{ url_for('article.tag_del', id=v.id) }}">删除</a>
                </td>
            </tr>
            {% endfor %}
        </table>
        {{ pg.page(auth_page, "article.tag_list") }}
    </div>


{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

{% endblock %}