apps/user/views.py
import os
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, g, make_response, abort, \
    flash
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash  # 密码加盐
from flask_login import login_required, logout_user, login_user, current_user

from apps.article.form import BlogPostForm
from apps.article.model import Blog
from apps.user.model import *
from apps.user.form import *
from apps.user.email import *
from apps.auth.model import *
from functools import wraps
import uuid

user_bp = Blueprint("user", __name__, url_prefix='/user')


# 模板中使用权限变量（针对蓝图）
@user_bp.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


"""
def decorator(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print("被装饰的函数 增加新功能")
        return func(*args, **kwargs)
    return wrapper
    
# 1、decorator 要返回 一个函数
# 2、将 被装饰的函数func 作为 decorator 的参数
# 3、func被装饰后 __name__会变为 wrapper
# 4、@wraps 使 __name__ 不变
# 5、当你使用@my_decorator语法时，你是在应用一个以单个函数作为参数的一个包裹函数 （func：被装饰的函数 作为参数）
"""


# 通过装饰器传参数，让装饰器自己接受参数
def need_permission(perm):
    # 自定义装饰器：角色权限访问控制装饰器
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            if not current_user.can(perm):
                abort(403)
            return func(*args, **kwargs)
        return wrapper
    return decorator


# 钩子函数: 请求前执行，应用再全局蓝图上
@user_bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.ping()
    # 登录了 and 没confirmed and 访问的不是user_bp and 不是静态文件的请求
    if current_user.is_authenticated \
            and not current_user.confirmed \
            and request.blueprint != 'user' \
            and request.endpoint != 'static' :
        flash("请前往邮箱，确认注册链接")
        return redirect(url_for('user.user_unconfirmed'))


# 未确认注册链接的用户限制在 user_unconfirmed.html
@user_bp.route('/unconfirmed/')
def user_unconfirmed():
    # print("current_user.is_anonymous", current_user.is_anonymous)
    # 未注册的匿名用户 or confirmed的用户 直接去首页
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('user.index'))
    return render_template('user/user_unconfirmed.html')


# 0.初始化数据库
@user_bp.route("/init_db/")
def init_db():
    Role.insert_roles()
    print("数据库初始化：")
    print(Role.query.all())
    return redirect(url_for('user.index'))


# # 1.用户注册
# @user_bp.route("/add", methods=["GET", "POST"])
# def user_add():
#     form = RegistForm()
#     if form.validate_on_submit():
#         user = User(
#             name=form.register_name.data,
#             email=form.register_email.data.lower(),
#             phone=form.register_phone.data,
#             pwd=generate_password_hash(form.register_pwd.data),  # 加盐用户的密码
#             uuid=uuid.uuid4().hex  # 生成用户的唯一标志符
#         )
#         db.session.add(user)
#         db.session.commit()
#
#         # 发送登录邮件 前commit()数据库才能生成id
#         token = user.generate_confirmation_token()  # 对当前注册用户生成签名令牌
#         send_email(user.email, '确认注册邮件', 'email/confirm', user=user, token=token)
#
#         flash('已发送注册链接至您的邮箱，请前去确认!', 'warning')
#         return redirect(url_for('user.index'))
#     return render_template("user/user_add.html", form=form)


# 0.博客首页
@user_bp.route('/index/', methods=['GET', 'POST'])
def index():
    page = int(request.args.get('page', 1))
    form = BlogPostForm()
    # 匿名用户可以看，但不能添加博客
    if not current_user.is_anonymous and form.validate_on_submit():
        blog = Blog(
            body=form.body.data,
            user=current_user._get_current_object(),  # current_user只是用户对象的轻度包装。_get_current_object()返回数据库需要的真正用户对象
        )
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('user.index'))

    # 显示关注人的博客
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_blogs  # Model里的property方法
    else:
        query = Blog.query

    blog_page = query.order_by(
        Blog.timestamp.desc()
    ).paginate(page=page, per_page=5)
    blogs = blog_page.items  # 返回分页后的项目
    return render_template("index.html", form=form, blogs=blogs, blog_page=blog_page)


# 邮件确认链接生成
@user_bp.route('/confirm/<token>/')
@login_required
def user_confirm(token):
    if current_user.confirmed:
        return redirect(url_for('user.index'))
    if current_user.confirm(token):
        db.session.commit()
        flash('您已注册成功！', 'info')
    else:
        flash('注册链接无效或过期', 'warning')
    return redirect(url_for('user.index'))


# 重新发送确认链接
@user_bp.route('/confirm/')
@login_required
def user_resend_confirmation():
    token = current_user.generate_confirmation_token()
    send_email(current_user.email, '确认注册邮件', 'email/confirm', user=current_user, token=token)
    flash('重新向您的邮箱发送了注册链接')
    return redirect(url_for('user.index'))


# 2.用户登录
@user_bp.route('/login/', methods=['GET', 'POST'])
def user_login():
    loginform = LoginForm()
    registerform = RegistForm()
    # 登录
    if loginform.login_submit.data and loginform.validate_on_submit():
        user = User.query.filter_by(name=loginform.login_name.data).first()
        if not user:
            flash("没有此用户名!", "temp")
            return redirect(url_for("user.user_login"))
        if not user.check_pwd(pwd=loginform.login_pwd.data):
            flash("密码错误!", "temp")
            return redirect(url_for("user.user_login"))

        # # 登录成功 保存session
        # session["user"] = user.name
        # session["user_id"] = user.id
        login_user(user)  # flask_login

        # 登录操作存入登录日志
        userlog = Userlog(
            user_id=current_user.id,
            ip=request.remote_addr,  # 获取IP
        )
        db.session.add(userlog)
        db.session.commit()

        return redirect(url_for("user.user_center"))
    # 注册
    elif registerform.register_submit.data and registerform.validate_on_submit():
        user = User(
            name=registerform.register_name.data,
            email=registerform.register_email.data.lower(),
            # phone=registerform.register_phone.data,
            pwd=generate_password_hash(registerform.register_pwd.data),  # 加盐用户的密码
            uuid=uuid.uuid4().hex  # 生成用户的唯一标志符
        )
        db.session.add(user)
        db.session.commit()

        # 发送登录邮件 前commit()数据库才能生成id
        token = user.generate_confirmation_token()  # 对当前注册用户生成签名令牌
        send_email(user.email, '确认注册邮件', 'email/confirm', user=user, token=token)
        # 登录
        login_user(user)
        flash('已发送注册链接至您的邮箱，请前去确认!', 'warning')
        #  未验证邮箱的用户会先出发钩子函数
        return redirect(url_for('user.index'))
    return render_template("user/user_login.html", loginform=loginform, registerform=registerform)


# 3.用户登出
@user_bp.route('/logout/')
@login_required
def user_logout():
    logout_user()  # flask_login
    return redirect(url_for('user.index'))


# 4.用户中心
@user_bp.route('/center/', methods=['GET', 'POST'])
@login_required
@need_permission(Permission.WRITE)
def user_center():
    form = UserdetailForm()
    user = User.query.get_or_404(current_user.id)  # 用户名不存在则404
    blogs = user.blogs.order_by(Blog.timestamp.desc()).all()  # 通过关系获得user的blogs，不加lazy='dynamic'排序order_by会报错
    # 前台展示用户当前信息
    if request.method == "GET":
        form.name.data = user.name
        form.email.data = user.email
        # form.phone.data = user.phone
        form.info.data = user.info
        form.location.data = user.location
        form.real_name.data = user.real_name

    # 修改信息
    if form.validate_on_submit():
        # 如果信息在库内已存在 + 提交的信息不是原信息，则修改失败
        # TODO:修改姓名按钮 + 用验证码修改手机号
        # user_name = User.query.filter_by(name=form.name.data).count()
        # if user_name == 1 and form.name.data == user.name:
        #     flash("用户昵称已存在,请重新输入!", "error")
        #     return redirect(url_for('user.user_center'))
        # user_email = User.query.filter_by(email=form.email.data.lower()).count()
        # if user_email == 1 and form.email.data.lower() == user.email:
        #     flash("用户邮箱已存在,请重新输入!", "error")
        #     return redirect(url_for('user.user_center'))
        # user_phone = User.query.filter_by(phone=form.phone.data).count()
        # if user_phone == 1 and form.phone.data == user.phone:
        #     flash("用户手机已存在,请重新输入!", "error")
        #     return redirect(url_for('user.user_center'))

        # 修改头像
        if form.face.data:
            face_name = secure_filename(form.face.data.filename)  # secure_filename规范化文件名
            form.face.data.save(os.path.join(current_app.config['UPLOAD_DIR'] + "\\avatar", face_name))
            user.face = os.path.join("upload/", face_name)  # 库里记录 static 下的路径

        # user.name = form.name.data
        # user.email = form.email.data
        # user.phone = form.phone.data
        user.info = form.info.data
        user.location = form.location.data
        user.real_name = form.real_name.data
        db.session.add(user)
        db.session.commit()
        flash('修改资料成功!', 'info')
        return redirect(url_for('user.user_center'))
    return render_template("user/user_center.html", form=form, user=user, blogs=blogs)


# 5.修改密码
@user_bp.route("/pwd/", methods=["GET", "POST"])
@login_required
def user_pwd():
    form = PwdForm()
    user = User.query.filter_by(id=current_user.id).first()
    if form.validate_on_submit():
        if not user.check_pwd(form.old_pwd.data):
            flash('旧密码错误!请重新输入!', 'temp')
            return redirect(url_for('user.user_pwd'))
        user.pwd = generate_password_hash(form.new_pwd.data)
        db.session.add(user)
        db.session.commit()
        flash('修改密码成功!请重新登录', 'info')
        return redirect(url_for('user.user_logout'))
    return render_template("user/user_pwd.html", form=form)


# 6.重设密码
@user_bp.route("/reset_pwd/", methods=["GET", "POST"])
def user_reset_pwd_request():
    # 匿名用户才进重设密码

templates/user/followers.html
{% extends "base.html"%}
{% import "ui/list_page.html" as pg%}
{% block title %}会员中心{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        .profile-thumbnail {
            position: absolute;
        }

        ul.blogs {
            list-style-type: none;{# 设置列表项标记的类型 #}
            padding: 0px;
            margin: 16px 0px 0px 0px;
            border-top: 1px solid #e0e0e0;
        }

        ul.blogs li.blog {
            padding: 8px;
            border-bottom: 1px solid #e0e0e0;
        }

        {# 鼠标以上去背景变色 #}
        ul.blogs li.blog:hover {
            background-color: #f0f0f0;
        }

        div.blog-date {float: right;}
        div.blog-user {font-weight: bold;}

        div.blog-content {
            margin-left: 48px;
            min-height: 48px;
        }

    </style>
{% endblock %}

{% block main %}

    <div class="page-header">
        <h1>{{ title }} {{ user.name }}</h1>
    </div>
    <table class="table table-hover followers">
        <thead><tr><th>User</th><th>Since</th></tr></thead>
        {% for i in follows %}
            <tr>
                <td>
                    <a href="{{ url_for('user.user_detail', uid = i.user.id) }}">
    {#                    <img class="img-rounded" src="">#}
                        {{ i.user.name }}
                    </a>
                </td>
                <td>{{ moment(i.timestamp).format('L') }}</td>
            </tr>
        {% endfor %}
    </table>
    {{ pg.page(pagination, "user" + endpoint, uid=user.id) }}
{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

{% endblock %}

templates/user/user_center.html
{% extends "base.html"%}

{% block title %}会员中心{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        .profile-thumbnail {
            position: absolute;
        }

        ul.blogs {
            list-style-type: none;{# 设置列表项标记的类型 #}
            padding: 0px;
            margin: 16px 0px 0px 0px;
            border-top: 1px solid #e0e0e0;
        }

        ul.blogs li.blog {
            padding: 8px;
            border-bottom: 1px solid #e0e0e0;
        }

        {# 鼠标以上去背景变色 #}
        ul.blogs li.blog:hover {
            background-color: #f0f0f0;
        }

        div.blog-date {float: right;}
        div.blog-user {font-weight: bold;}

        div.blog-content {
            margin-left: 48px;
            min-height: 48px;
        }

    </style>
{% endblock %}

{% block main %}
    {% with msgs = get_flashed_messages(with_categories=True) %}
      {% if msgs %}
          <ul id="flashToasts" hidden>
              {% for category, msg in msgs %}
                  <li class="{{ category }}" >{{ msg }}</li>
              {% endfor %}
          </ul>
      {% endif %}
    {% endwith %}

    <div id="role">
{#        enctype="multipart/form-data" 上传文件的表单需要添加。既有文本数据，又有二进制数据#}
        <form action="{{ url_for('user.user_center') }}" method="post" enctype="multipart/form-data">

            <p>
                {{ form.name.label }}
                {{ form.name(readonly=True) }}
                <a href="">修改</a>
                {% for message in form.name.errors %}
                        <small class="error">{{ message }}</small><br>
                {% endfor %}
            </p>

            <p>
                {{ form.email.label }}
                {{ form.email(readonly=True, style='width:50%; color: #0c84ff') }}
{#                {{ user.email }}#}
                <a href="{{ url_for('user.user_change_email_request') }}">修改</a>
                {% for message in form.email.errors %}
                    <small class="error">{{ message }}</small><br>
                {% endfor %}
            </p>

{#            <p>#}
{#                {{ form.phone.label }}#}
{#                {{ form.phone(readonly=True, style='font-size:24px; color:red') }}#}
{#                {{ user.phone }}#}
{#                <a href="">修改</a>#}
{#                {% for message in form.phone.errors %}#}
{#                    <small class="error">{{ message }}</small><br>#}
{#                {% endfor %}#}
{#            </p>#}

            <p>{{ form.face.label }}{{ form.face }}</p>

            <p>
                {# 如果存在头像,就显示出来,否则,就显示默认头像 #}
                <img src=" {% if user.face %} {{ url_for('static', filename=user.face) }} {% else %} {{ url_for('static', filename='/upload/defaultAvator.jpg') }} {% endif %}" width="50px" height="50px" alt="头像加载失败">
                {% for message in form.face.errors %}
                    <small class="error">{{ message }}</small><br>
                {% endfor %}
            </p>

            <p>
                {{ form.info.label }}{{ form.info }}
                {% for message in form.info.errors %}
                    <small class="error">{{ message }}</small><br>
                {% endfor %}
            </p>

            <p>
                {{ form.location.label }}{{ form.location }}
                {% for message in form.location.errors %}
                    <small class="error">{{ message }}</small><br>
                {% endfor %}
            </p>

            <p>
                {{ form.real_name.label }}{{ form.real_name }}
                {% for message in form.real_name.errors %}
                    <small class="error">{{ message }}</small><br>
                {% endfor %}
            </p>

            <p>
                <a href="{{ url_for('user.user_pwd') }}">修改密码</a>
            </p>

            <p>
                {{ form.submit(style='
                    color: #000000;
                    font-size: 16px;
                    border: 1px solid #e5e5e5;
                    padding: 10px 25px;
                    display: inline-block;
                    background-color: #d7d7d7;
                    font-weight: 600;
                    cursor: pointer;
                ') }}
                {{ form.csrf_token }}
            </p>
      </form>
    <button><a href="{{ url_for('user.index') }}">首页</a></button>
    <button><a href="{{ url_for('article.article_add') }}">添加文章</a></button>
    {% if current_user.can(Permission.MODERATE) %}
        <button><a href="{{ url_for('article.comment_list') }}">管理评论</a></button>
    {% endif %}

    {% if not current_user.confirmed %}
        请前往邮箱，确认注册链接。<a href="{{ url_for('user.user_resend_confirmation') }}">点击获取注册链接</a>
    {% endif %}

    <p>注册时间 {{ moment(user.addtime).format('MMMM Do YYYY, h:mm:ss a') }}.</p>
    <p>最近访问时间 {{ moment(user.last_seen).fromNow(refresh=True) }}</p>

    </div>

    {% if blogs %}
        <div>
            <b>您发布的Blog有：</b>
            {% include 'ui/_blogs.html' %}
        </div>
    {% endif %}

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

{% endblock %}

templates/user/user_login.html
{% extends "base.html"%}

{% block title %}登录注册{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        html,
        body {
          height: 100%;
        }

        body {
          display: -ms-flexbox;
          display: flex;
          -ms-flex-align: center;
          align-items: center;
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: #f5f5f5;
        }

        .form-signin {
          width: 100%;
          max-width: 430px;
          padding: 15px;
          margin: auto;
        }

        .form-borderline {
            width: 100%;
            max-width: 360px;
            padding: 0px 25px 25px 25px;
            margin: auto;
            border: 1px solid rgb(222, 223, 224);
            border-radius: 4px;
        }

        .form-borderline ul {
                border-bottom: 1px solid rgb(222, 223, 224);
        }

        .bottom-line {
            color: rgb(95, 99, 104);
            font-size: 1.1rem;
            height: 100%;
            display: flex;
            white-space: nowrap;
            -webkit-box-align: center;
            align-items: center;
            position: relative;
        }

        .bottom-line span {
            position: absolute;
            bottom: 0px;
            left: 0px;
            height: 3px;
            width: 100%;
            background-color: rgb(32, 33, 36);
            border: none;
            border-radius: 3px 3px 0px 0px;
        }

        .bottom-flex {
            display: flex;
            justify-content: space-between;
            margin-top: 24px;
        }

        .bottom-flex button {
            padding: 0px 24px;
            border-radius: 20px;
            height: 36px;
            align-items: center;
            font-weight: 700;
            background-color:#F5F5F5;
            border-color: #F5F5F5;
        }

        .form-signin .checkbox {
          font-weight: 400;
        }

        .form-signin .form-control {
          position: relative;
          box-sizing: border-box;
          height: auto;
          padding: 10px;
          font-size: 16px;
        }

        .form-signin .form-control:focus {
          z-index: 2;
        }

        .form-signin input[type="email"] {
          margin-bottom: -1px;
          border-bottom-right-radius: 0;
          border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
          margin-bottom: 10px;
          border-top-left-radius: 0;
          border-top-right-radius: 0;
        }

        .urllink {
            color: rgb(0, 138, 188);
            text-decoration: none;
            cursor: pointer;
        }

        .urllink:hover {
            color: #20beff;
            text-decoration: none;
            cursor: pointer;
        }

    </style>
{% endblock %}

{% block body %}
    <div class="text-center form-signin">
        <img class="mb-4" src="{{ url_for('static', filename='upload/logo/bootstrap-solid.svg') }}" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">欢迎使用AICenter</h1>

        <div class="form-borderline">

            <ul class="nav mb-3" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                        <a class="nav-link bottom-line active" id="pills-login-tab" data-toggle="pill" href="#pills-login" role="tab" aria-controls="pills-login" aria-selected="true">
                            登录
{#                            <span></span>#}
                        </a>
                </li>
                <li class="nav-item" role="presentation">
                        <a class="nav-link bottom-line" id="pills-register-tab" data-toggle="pill" href="#pills-register" role="tab" aria-controls="pills-register" aria-selected="false">
                            注册
{#                            <span></span>#}
                        </a>

                </li>
            </ul>

            <div class="tab-content" id="pills-tabContent">
                {# 登录 #}
                <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="pills-login-tab">
                    {# TODO: 邮箱登录 & 流式表单 & 忘记用户名 #}
                    <form class="needs-validation" novalidate action="{{ url_for('user.user_login') }}" method="post">
                        <p>
                            {{ loginform.login_name.label(class="sr-only") }}{{ loginform.login_name }}
                            {% if loginform.login_name.errors %}
                                <small>{{ loginform.login_name.errors.0 }}</small>
                            {% endif %}
                        </p>

                        <p>
                            {{ loginform.login_pwd.label(class="sr-only") }}{{ loginform.login_pwd }}
                            {% if loginform.login_pwd.errors %}
                                <small>{{ loginform.login_pwd.errors.0 }}</small>
                            {% endif %}
                        </p>

                        <div class="bottom-flex">
                            <button type="reset" class="btn btn-light" onclick="window.location.href='{{ url_for('user.index') }}'">返回</button>
{#                            <a role="button" class="btn btn-light" href="{{ url_for('user.index') }}">返回</a>#}
                            {{ loginform.login_submit }}{{ loginform.csrf_token(id="login_csrf_token") }}
                        </div>

                        <div style="margin-top: 36px">
                            忘记
                            <a class="urllink" href="#">用户名</a>
                            <span> / </span>
                            <a class="urllink" href="{{ url_for('user.user_reset_pwd_request') }}">密码</a>
                            ？
                        </div>
                    </form>
                </div>

                {# 注册 #}
                <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="pills-register-tab">

                    <form class="needs-validation" novalidate action="{{ url_for('user.user_login') }}" method="post">
                        <p>
                            {{ registerform.register_name.label(class="sr-only") }}{{ registerform.register_name }}
                            {% if registerform.register_name.errors %}
                                <small>{{ registerform.register_name.errors.0 }}</small>
                            {% endif %}
                        </p>

                        <p>
                            {{ registerform.register_email.label(class="sr-only") }}{{ registerform.register_email }}
                            {% if registerform.register_email.errors %}
                                <small>{{ registerform.register_email.errors.0 }}</small>
                            {% endif %}
                        </p>

{#                        <p>#}
{#                            {{ registerform.register_phone.label(class="sr-only") }}{{ registerform.register_phone }}#}
{#                            {% if registerform.register_phone.errors %}#}
{#                                <small>{{ registerform.register_phone.errors.0 }}</small>#}
{#                            {% endif %}#}
{#                        </p>#}

                        <p>
                            {{ registerform.register_pwd.label(class="sr-only") }}{{ registerform.register_pwd }}
                            {% if registerform.register_pwd.errors %}
                                <small>{{ registerform.register_pwd.errors.0 }}</small>
                            {% endif %}
                        </p>

                        <p>
                            {{ registerform.register_repwd.label(class="sr-only") }}{{ registerform.register_repwd }}
                            {% if registerform.register_repwd.errors %}
                                <small>{{ registerform.register_repwd.errors.0 }}</small>
                            {% endif %}
                        </p>

                        <div class="bottom-flex">
                            <button type="reset" class="btn btn-light" onclick="window.location.href='{{ url_for('user.index') }}'">返回</button>
                            {{ registerform.register_submit }}{{ registerform.csrf_token(id="register_csrf_token") }}
                        </div>
                    </form>

                </div>

            </div>

            {% with msgs = get_flashed_messages(with_categories=True) %}
                  {% if msgs %}
                      <ul>
                          {% for category, msg in msgs %}
                              <li class="{{ category }}" >{{ msg }}</li>
                          {% endfor %}
                      </ul>
                  {% endif %}
            {% endwith %}
        </div>

        <p class="mt-5 mb-3 text-muted">&copy; 2022-2023</p>
    </div>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

<script src="{{ url_for('static', filename='extends/jbvalidator/jbvalidator.min.js') }}"></script>
<script>
    $(function (){
        // 载入页面时，将 active 的标签加入 span
         $(".bottom-line").each(function () {
             if($(this).hasClass("active")) {
                 $(this).css("color", "rgb(32, 33, 36)")
                 $(this).append("<span></span>")
             }
        })

        // jbvalidator 客户端表单验证
        let validator = $('form.needs-validation').jbvalidator({
            errorMessage: true,
            successClass: true,
            // 配置默认验证信息
            {#language: "https://emretulek.github.io/jbvalidator/dist/lang/tr.json",#}
            language: "{{ url_for('static', filename='extends/jbvalidator/ch.json') }}",
        });

        //custom validate methode
        validator.validator.custom = function(el, event){
            if($(el).is('[name=login_name]') && $(el).val().length < 3){
                return 'Your password is too weak.';
            }

        }

        {#validator.checkAll();  // 在不提交表单的情况下显示错误，返回错误计数#}
        {#validator.errorTrigger();  // 显示从服务器返回的错误消息#}
        validator.reload();  // 添加动态元素后重新加载实例
    })

    // 点击事件加入span
    $("#pills-login-tab").click(function () {
        $(this).append("<span></span>")
        $(this).css("color", "rgb(32, 33, 36)")
        $("#pills-register-tab").find("span").remove()
        $("#pills-register-tab").css("color", "rgb(95, 99, 104)")
    })
    $("#pills-register-tab").click(function () {
        $(this).append("<span></span>")
        $(this).css("color", "rgb(32, 33, 36)")
        $("#pills-login-tab").find("span").remove("span")
        $("#pills-login-tab").css("color", "rgb(95, 99, 104)")
    })


</script>
{% endblock %}

templates/user/user_pwd.html
{% extends "base.html"%}

{% block title %}修改密码{% endblock %}

{% block main %}

    <div id="role">

        <form action="{{ url_for('user.user_pwd') }}" method="post">

        <p>{{ form.old_pwd.label }}{{ form.old_pwd }}</p>
            {% for message in form.old_pwd.errors %}
                    <small class="error">{{ message }}</small><br>
            {% endfor %}
        <p>{{ form.new_pwd.label }}{{ form.new_pwd }}</p>
            {% for message in form.new_pwd.errors %}
                <small class="error">{{ message }}</small><br>
            {% endfor %}
        <p>{{ form.submit }}{{ form.csrf_token }}</p>

      </form>

    </div>


{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

{% endblock %}

templates/user/user_reset_pwd.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}重设密码{% endblock %}

{% block main %}

    <div id="role">

        {{ wtf.quick_form(form) }}

    </div>


{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

{% endblock %}

templates/user/user_unconfirmed.html
{% extends "base.html"%}

{% block title %}注册链接确认{% endblock %}

{% block main %}
    <h1>
        Hello,
        {% if current_user.is_authenticated %}
            {{ current_user.name }}
        {% else %}
            Stranger
        {% endif %}!
    </h1>

    <h2>请前往邮箱，确认注册链接</h2>
    <h3><a href="{{ url_for('user.user_resend_confirmation') }}">点击获取注册链接</a></h3>

{% endblock %}


<!--js脚本-->
{% block scripts %}
{{ super() }}

{% endblock %}